USE nexus_med;

INSERT INTO products 
(id, name, brand, category, description, dosage, pack_size, price, original_price, stock_count, requires_rx, image_url, badge, rating, reviews_count, active_ingredient, usage_instructions, side_effects) 
VALUES
(
  'med-001', 
  'NexusPar 650 Fast-Relief', 
  'Nexus Health Pharma', 
  'pain-relief', 
  'Effective symptomatic treatment for mild to moderate pain, headache, muscle soreness, and high fever reduction.', 
  '650 mg', 
  '15 Tablets Strip', 
  38.00, 
  50.00, 
  150, 
  FALSE, 
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80', 
  'BESTSELLER',
  4.80,
  342,
  'Paracetamol / Acetaminophen (650mg)',
  'Take 1 tablet every 6 hours after food as required. Do not exceed 4 tablets in 24 hours.',
  'Mild nausea, rare allergic rash'
),
(
  'med-002', 
  'Amoxil-CV 625 Triple Care', 
  'Nexus Specialty RX', 
  'antibiotics', 
  'Broad-spectrum antibiotic prescription medicine for respiratory tract infections, sinus, and ear infections.', 
  '500mg Amoxicillin + 125mg Clavulanate', 
  '10 Tablets Strip', 
  210.00, 
  260.00, 
  45, 
  TRUE, 
  'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=600&q=80', 
  'RX REQUIRED',
  4.90,
  189,
  'Amoxicillin Trihydrate & Potassium Clavulanate',
  'Take strictly as prescribed by a licensed physician with meals twice daily.',
  'Mild diarrhea, stomach discomfort'
),
(
  'med-003', 
  'NexusVite Active Immunity C+Zinc', 
  'Nexus Nutrition', 
  'vitamins', 
  'Effervescent antioxidant daily health supplement for robust cellular defense, collagen synthesis, and stamina.', 
  '1000mg Vit C + 10mg Zinc', 
  '20 Effervescent Tablets', 
  299.00, 
  399.00, 
  220, 
  FALSE, 
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAmB8YQp_EONpvvn_Az2lgSbDhmKaCGtU-621D9J_Ikg&s=10', 
  '25% OFF',
  4.70,
  512,
  'L-Ascorbic Acid & Zinc Sulphate',
  'Dissolve 1 tablet in a glass of 200ml fresh cold water daily in the morning.',
  'None noted when taken as directed'
),
(
  'med-004', 
  'GlucoGuard SR 500', 
  'Nexus Endocrine Care', 
  'diabetes-cardiac', 
  'Sustained-release antihyperglycemic oral medication for Type-2 Diabetes management and glycemic stability.', 
  '500 mg', 
  '15 Sustained Release Tablets', 
  65.00, 
  80.00, 
  95, 
  TRUE, 
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSu1BvN3GWkCS68ti_EgL8rkyD3pv1p5-k_AIGMLt3Z9g&s', 
  'RX REQUIRED',
  4.60,
  140,
  'Metformin Hydrochloride (500mg SR)',
  'Administer with evening meals or as recommended by endocrinologist.',
  'Initial bloating, metabolic equilibrium shift'
),
(
  'med-005', 
  'Pantop-D Rapid Gel Caps', 
  'Nexus Gastro Lab', 
  'digestive', 
  'Dual action proton pump inhibitor + prokinetic for hyperacidity, GERD, acid reflux and heartburn relief.', 
  '40mg Pantoprazole + 30mg Domperidone', 
  '15 Hard Capsules Strip', 
  145.00, 
  180.00, 
  80, 
  FALSE, 
  'https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&w=600&q=80', 
  'FAST ACTION',
  4.80,
  278,
  'Pantoprazole Sodium & Domperidone SR',
  'Swallow whole 30 minutes before breakfast with water.',
  'Dry mouth, headache'
),
(
  'med-006', 
  'DermAClear Antiseptic Cream', 
  'Nexus Skincare Science', 
  'personal-care', 
  'Soothing dermatological healing ointment for minor cuts, burns, skin abrasions, and topical irritation.', 
  '1% Chlorhexidine + 15% Cetrimide', 
  '50g Tube', 
  120.00, 
  150.00, 
  110, 
  FALSE, 
  'https://images.unsplash.com/photo-1608248597560-8412674e2d3d?auto=format&fit=crop&w=600&q=80', 
  'TOP RATED',
  4.90,
  405,
  'Chlorhexidine Gluconate',
  'Clean affected skin surface gently and apply a thin layer 2-3 times daily.',
  'Mild local stinging'
)
ON DUPLICATE KEY UPDATE 
name=VALUES(name), price=VALUES(price), stock_count=VALUES(stock_count);
